### ISSUE TITLE
Shopify Product Inventory View improvements

### ISSUE THREAD

**Issue by gurveenbagga** [hotwax/ofbiz-mantle-udm#8]
1. The Shopify Product inventory view should be improved to handle the below scenarios.
    1. Facility ON/OFF 
        1. If Facility is OFF, then earlier the maxOrderLimit is set to 0, but now this means that the facility is off only for fulfillment but this does not mean we should exclude this facility's inventory.
        2. If Facility's inventory should participate in eComm, then it should be part of the Online Facility Group, 'SHOPIFY_GROUP_FAC'.
        3. If Facility's inventory should not participate in eComm, then it should not be part of the Online Facility Group, 'SHOPIFY_GROUP_FAC', so the FacilityGroupMember record is expired.
    2. Product ON/OFF 
        1. For Product OFF, allowBrokering is set to N for a Facility in ProductFacility entity, then we need to check if the Facility is active(ON), then that atp should be deducted from the atp.
        2. For Product ON, allowBrokering will be either null or Y.
    3. Missing UPC or variant id for Product
        1. If for product, there is no UPC or Product Variant Id, then we should not send it as part of the Shopify Inventory feed.
            1. UPC value refers to the idValue for Good Identification Type Id as UPCA.
            2. Product Variant Id refers to the Product.internalName.
     4. The Safety Stock should also be deducted from the final atp.
         1. NOTE: As the computedLastInventoryCount field of ProductFacility already deducts the value of minimumStock, so no need to add extra handling.

**Comment by janvi04** [comment]
**Product Inventory recorded for valid UPC against invalid facility**

**Use case:** 
1. A product - 174873 (https://sm-uat.hotwax.io/commerce/control/FindProductInventory?productId=174873) that belonged to DV_STORE at facility 977. Its inventory was recorded for facility 1 as well.
2. Here facility 1 is not a part of DV_STORE. Hence when fetching the inventory for this product we get incorrect atp as inventory from facility 977 as well as for facility 1 was fetched.
3. The possible solution was to include ProductStoreFacility in the ShopifyProductInventory to get only those facilities that are associated with a particular Product Store and get the correct atp for a product.

**The issue with joining ProductStoreFacility in the ShopifyProductInventory view was that:**
1. If we join ProductStoreFacility with ShopifyShop on productStoreId then we get both the facilities associated with DV_STORE which is incorrect as facility 1 is not associated with DV_STORE.
This will give incorrect results as when we fetch the products for DV_STORE we will get the inventory recorded for facility 1 as well.
2. If we join ProductStoreFacility with ProductFacility on facilityId and get the productStoreId field from the PSF instead of SS, then we get the correct facility associated with the facility but we still get the product on facility 1 associated with SM_STORE and SG_STORE.
This will give incorrect results as when we fetch the products for SM_STORE we will get the inventory for products associated with DV_STORE as well.

ProductId: 174873 associated with DV_STORE at facility 977 and facility 1(SM_STORE and SG_STORE).

When fetching the records we want only the inventory recorded at facility 977.

**Solution**
1. Not including ProductStoreFacility directly in the ShopifyProductInventory.
2. Create another view ProductStoreFacilityAndShopifyInventory with member entities as ProductStoreFacility and ShopifyProductInventory view. We have used sub-select on ShopifyProductInventory view that will get the product associated with correct facilities and product stores.
3. The condition of join between ProductStoreFacility and ShopifyProductInventory is
    1. facilityId
    2. productStoreId
4. The sum and max functions are applied on the fields of ShopifyProductInventory again as we were not getting the desired results by applying the functions in these fields on the ShopifyProductInventory view only.
